### ISSUE TITLE
can you realease a readme.md ?

### ISSUE THREAD

**Issue by lulia0228** [DeligientSloth/SiameseBert#1]
Hello, i'm very Interested in s-bert similarity analysis, didi you experienced in real data, such as STS data？

**Comment by DeligientSloth** [comment]
> Hello, i'm very Interested in s-bert similarity analysis, didi you experienced in real data, such as STS data？

OK, but siamese Bert doesn't perform well in my dataset, my data is query-question pair data, what is STS data, describe?

**Comment by DeligientSloth** [comment]
> Hello, i'm very Interested in s-bert similarity analysis, didi you experienced in real data, such as STS data？

sia

**Comment by lulia0228** [comment]
Oh, I'm sorry. It's SST data for text similarity task.
